"""Structured Output Compiler: raw LLM text -> Markdown report + validated actions."""

from __future__ import annotations

import json
import logging
import re
import uuid
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from app.config import settings

logger = logging.getLogger(__name__)

_ACTIONS_HEADER = "### ACTIONS"
_JSON_LINE = re.compile(r"^\s*\{.*\}\s*$")


class ActionBlock(BaseModel):
    """A structured downstream system action emitted by the reasoning core."""
    action: str = Field(min_length=1)
    target: str | None = None
    parameters: dict[str, Any] = Field(default_factory=dict)


class ReasoningResult(BaseModel):
    """Validated Phase 4 output contract."""
    query_id: str
    backend_used: str
    answer_text: str
    actions: list[ActionBlock] = Field(default_factory=list)
    report_path: str
    pruning: dict[str, Any]
    context_bytes: int


def parse_actions(answer_text: str) -> tuple[str, list[ActionBlock]]:
    """Split answer body from the ACTIONS section; validate each JSON line.

    Malformed action lines are collected into a permissive ActionBlock with
    action="unparsed" instead of failing the whole report (robust formatting).
    """
    text = answer_text
    actions: list[ActionBlock] = []
    if _ACTIONS_HEADER in answer_text:
        body, _, action_section = answer_text.partition(_ACTIONS_HEADER)
        text = body.strip()
        for line in action_section.strip().splitlines():
            if not _JSON_LINE.match(line):
                continue
            try:
                raw = json.loads(line)
                if isinstance(raw, dict):
                    actions.append(ActionBlock.model_validate(raw))
            except (json.JSONDecodeError, Exception) as exc:  # noqa: BLE001 - robust per-line
                logger.warning("Unparseable action line skipped", extra={"reason": str(exc)})
                actions.append(ActionBlock(
                    action="unparsed", target=None,
                    parameters={"raw": line.strip()[:500]},
                ))
    return text, actions


def build_markdown_report(
    query: str, backend_used: str, answer_text: str,
    actions: list[ActionBlock], pruning: dict[str, Any],
) -> str:
    """Render a clean downloadable Markdown report."""
    lines = [
        f"# Reasoning Report",
        "",
        f"- **Query:** {query}",
        f"- **Backend:** `{backend_used}`",
        f"- **Context:** {pruning.get('kept_items', 0)}/{pruning.get('input_items', 0)} blocks kept "
        f"({pruning.get('tokens_after', 0)} / {pruning.get('budget', 0)} tokens, "
        f"{pruning.get('dropped', 0)} dropped)",
        "",
        "## Answer",
        "",
        answer_text,
    ]
    if actions:
        lines += ["", "## Structured Actions", ""]
        for i, action in enumerate(actions, start=1):
            lines.append(
                f"{i}. **`{action.action}`** → `{action.target or 'n/a'}` "
                f"`{json.dumps(action.parameters)}`"
            )
    lines += ["", "---", f"_Generated by the Multimodal AI Ingestion Engine "
              f"(reasoning core)._"]
    return "\n".join(lines)


def compile_output(
    query: str, backend_used: str, answer_text: str, pruning: dict[str, Any],
    context_bytes: int, query_id: str | None = None,
) -> ReasoningResult:
    """Full compiler: parse actions, render the Markdown report, persist it."""
    query_id = query_id or uuid.uuid4().hex
    body, actions = parse_actions(answer_text)
    report = build_markdown_report(query, backend_used, body, actions, pruning)

    report_dir = settings.result_dir / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"report_{query_id}.md"
    report_path.write_text(report, encoding="utf-8")

    logger.info("Output compiled", extra={
        "query_id": query_id, "backend_used": backend_used,
        "actions": len(actions), "report_path": str(report_path),
    })
    return ReasoningResult(
        query_id=query_id, backend_used=backend_used, answer_text=body,
        actions=actions, report_path=str(report_path),
        pruning=pruning, context_bytes=context_bytes,
    )
